sudo: required
language: generic

services:
- docker

env:
  global:
  - TERM=dumb
  - MAKEFLAGS='--silent'
  matrix:
  - BUILD_TARGET=release
  - BUILD_TARGET=next

install:
  - docker run --name builder -e TERM -e MAKEFLAGS -v $PWD:$PWD -w $PWD -td snapcore/snapcraft
  - docker exec -i builder apt update
  - docker exec -i builder apt full-upgrade -y

before_script: .travis/version-prepare.sh

script:
  - docker exec -i builder snapcraft

after_success:
- openssl aes-256-cbc -K $encrypted_1ce1bbc103e7_key -iv $encrypted_1ce1bbc103e7_iv
  -in .snapcraft/travis_snapcraft.cfg -out .snapcraft/snapcraft.cfg -d

before_deploy:
  - docker exec -i builder snapcraft status remmina

deploy:
  - provider: script
    skip_cleanup: true
    script: docker exec -i builder snapcraft push *.snap --release beta
    on:
      condition: $BUILD_TARGET = release
  - provider: script
    skip_cleanup: true
    script: docker exec -i builder snapcraft push *.snap --release edge
    on:
      condition: $BUILD_TARGET != release

after_deploy:
  - docker exec -i builder snapcraft status remmina
